# Generic defaults

name: generic-server
namespace: gameservers

base:
  image: alpine
  tag: latest

config:
  name: generic-server-config
  templatePath: ""
  fileName: ""
  configPath: /data

steamcmd:
  appid: 0
  loginMode: anonymous
  secretName: ""

server:
  startCommand: ""

ports:
  - name: game
    containerPort: 7777
    protocol: UDP

features:
  copyMods:
    enabled: false
    source: /data/mods
    destination: /data/assets

pvc:
  enabled: true
  name: generic-data
  storageClassName: local-path
  size: 1Gi

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
