apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: gameservers
spec:
  containers:
    - name: shell
      image: debian:bookworm-slim
      command: ["/bin/sh"]
      stdin: true
      tty: true
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: starbound-data
