name: starbound-server
namespace: gameservers

config:
  name: starbound-server-config
  templatePath: games/starbound/data/starbound_server.config
  fileName: starbound_server.config
  configPath: /data/storage
  overwriteOnStart: true

steamcmd:
  appid: "211820"
  loginMode: credentials
  secretName: steam-credentials

server:
  startCommand: /data/linux/starbound_server -bootconfig /data/storage/starbound_server.config

ports:
  - name: game
    containerPort: 21025
    protocol: TCP
  - name: query
    containerPort: 21026
    protocol: TCP

pvc:
  enabled: true
  name: starbound-data
  storageClassName: local-path
  size: 2Gi

features:
  copyMods:
    enabled: true
    source: /data/mods
    destination: /data/assets

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "1"
    memory: "2Gi"
